spring:
  profiles:
    active: local
  application:
    name: tcc
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  account:
    email: seu_email@gmail.com
    password: senha

  twilio:
    id-conta: id
    token: token
    origem: 98908098

#  database:
#    url: url
#    user: user
#    password: password



